import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

interface EnsureDockerDeploymentFilesInput {
  hibossDir: string;
  outputDir: string;
  adminToken: string;
}

function resolveCurrentHibossVersion(): string | null {
  const envVersion = (process.env.HIBOSS_NPM_VERSION ?? "").trim();
  if (envVersion) return envVersion;

  let cursor = path.dirname(fileURLToPath(import.meta.url));
  for (let i = 0; i < 8; i++) {
    const candidate = path.join(cursor, "package.json");
    if (fs.existsSync(candidate)) {
      try {
        const parsed = JSON.parse(fs.readFileSync(candidate, "utf8")) as {
          name?: unknown;
          version?: unknown;
        };
        if (parsed.name === "hiboss" && typeof parsed.version === "string" && parsed.version.trim()) {
          return parsed.version.trim();
        }
      } catch {
        // best effort
      }
    }
    const parent = path.dirname(cursor);
    if (parent === cursor) break;
    cursor = parent;
  }

  return null;
}

function normalizeDockerBindPath(p: string): string {
  return p.replace(/\\/g, "/");
}

function dockerComposeBody(hibossDir: string): string {
  const bindPath = normalizeDockerBindPath(hibossDir);
  return `services:
  hiboss-daemon:
    image: node:22-bullseye
    container_name: hiboss-daemon
    env_file:
      - ./.env.docker
    command:
      - /bin/sh
      - -lc
      - >
        set -e;
        npm install -g @anthropic-ai/claude-code @openai/codex;
        if [ -n "\${HIBOSS_NPM_VERSION:-}" ]; then
          npm install -g "hiboss@\${HIBOSS_NPM_VERSION}";
        else
          npm install -g hiboss;
        fi;
        export PATH="/usr/local/bin:/usr/local/sbin:$PATH";
        if ! command -v hiboss >/dev/null 2>&1; then
          if [ -x /usr/local/lib/node_modules/hiboss/dist/bin/hiboss.js ]; then
            ln -sf /usr/local/lib/node_modules/hiboss/dist/bin/hiboss.js /usr/local/bin/hiboss;
          fi;
        fi;
        command -v hiboss >/dev/null 2>&1 || { echo "hiboss CLI missing from PATH after setup bootstrap" >&2; exit 1; };
        HIBOSS_MANAGED_RUNTIME=off HIBOSS_DIR=/hiboss hiboss daemon start;
        tail -F /hiboss/.daemon/daemon.log;
    environment:
      HIBOSS_DIR: /hiboss
      HIBOSS_MANAGED_RUNTIME: off
      IS_SANDBOX: \${IS_SANDBOX:-1}
      NODE_ENV: \${NODE_ENV:-production}
    restart: unless-stopped
    volumes:
      - "${bindPath}:/hiboss"
      - hiboss_root_home:/root
volumes:
  hiboss_root_home:
`;
}

function dockerEnvBody(adminToken: string): string {
  const version = resolveCurrentHibossVersion();
  return `# Auto-generated by hiboss setup
HIBOSS_TOKEN=${adminToken.trim().toLowerCase()}
${version ? `HIBOSS_NPM_VERSION=${version}` : "# HIBOSS_NPM_VERSION=<optional-pinned-version>"}
TZ=UTC
IS_SANDBOX=1
NODE_ENV=production
`;
}

export function getDefaultDockerDeploymentOutputDir(hibossDir: string): string {
  return path.join(hibossDir, "services", "hiboss-daemon");
}

export function ensureDockerDeploymentFiles(input: EnsureDockerDeploymentFilesInput): void {
  fs.mkdirSync(input.outputDir, { recursive: true });

  const composePath = path.join(input.outputDir, "docker-compose.yml");
  const envPath = path.join(input.outputDir, ".env.docker");

  fs.writeFileSync(composePath, dockerComposeBody(input.hibossDir), "utf8");
  fs.writeFileSync(envPath, dockerEnvBody(input.adminToken), "utf8");

  try {
    fs.chmodSync(envPath, 0o600);
  } catch {
    // best effort across platforms
  }
}
